### ISSUE TITLE
Can u add some new features?

### ISSUE THREAD

**Issue by Kleszcz123** [AnonVodka/Astrium#2]
Hi,
Can u add fake head witch changing side on key and some new antiaims to ur cheat (astrium) and new resolver? (I very like ur cheat, im using it everyday, but its not good on hvh :( ) With these features astrium will be better :)

Have a nice day <3

**Comment by CyclesProgramming** [comment]
its open source i wonder why........

**Comment by NekoRem** [comment]
it might be that this is a good legit hack then....
